### ISSUE TITLE
static linking on windows releases

### ISSUE THREAD

**Issue by Mathemalsky** [Mathemalsky/turinga#50]
Practical use showed that windows os often do not provide the `libstdc++-6.dll` file. Do avoid dependency of that file It could be useful to link staticly against this library for windows releases. But unfortunaly the compiler flag `-static-libstdc++` is ignored by clang.

**Comment by MilchRatchet** [comment]
Essentially, on Windows everything is supposed to be linked dynamically and static libraries in that sense do not really exist (`*.a` or `*.lib` generally link against some `*.dll`) Hence, the Windows way is to include the `*.dll` in your release. By default, Windows always first searches in the same directory as the executable for linking. For example, if you install Python on Windows, the standard libraries used for building Python are present in the same directory as the Python.exe.

Additionally, you are talking about the `libstdc++-6.dll` which is a GNU C++ standard library. If you want to not include a standard library `*.dll` you will probably have to use MSVC for building as that one will link against `msvcp*.dll` which should be present on most Windows platforms. Maybe it is possible to use other compilers and link against `msvcp*.dll` but I am not sure about that one.
